### PR TITLE
Add bitmap-save-classes parameter

### PR DESCRIPTION
**Pull request by matinlotfali**
In this pull request, I allow bitmap flagged saving on specific classes defined in the new bitmap-save-classes parameter.

### CODE REVIEW

**Comment by mistyron** [comment]
> In this pull request, I allow bitmap flagged saving on specific classes defined in the new bitmap-save-classes parameter.

Please explain how you tested & verified that this works as expected

**Comment by matinlotfali** [comment]
> > In this pull request, I allow bitmap flagged saving on specific classes defined in the new bitmap-save-classes parameter.
> 
> Please explain how you tested & verified that this works as expected

I ran the gstreamer and ensured that with property value set, it generates bitmaps.

**Comment by mistyron** [comment]
> In this pull request, I allow bitmap flagged saving on specific classes defined in the new bitmap-save-classes parameter.



> > > In this pull request, I allow bitmap flagged saving on specific classes defined in the new bitmap-save-classes parameter.
> > 
> > 
> > Please explain how you tested & verified that this works as expected
> 
> I ran the gstreamer and ensured that with property value set, it generates bitmaps.

Please mention which property you set to which value (or link to README if available) and mention the location where you can verify the presence of the bitmaps.

**Comment by matinlotfali** [comment]
> Please mention which property you set to which value (or link to README if available) 

I set the property **bitmap-save-classes** to `car,bus` as mentioned in https://github.com/MistySOM/gstreamer1.0-drpai/blob/develop/README.md

> and mention the location where you can verify the presence of the bitmaps.

I verify the presence of low-probability cars and busses bitmap images in the working directory.

**Pull request merged**
